.\"                                      Hey, EMACS: -*- nroff -*-
.TH ROBOCUT 1 "October 31, 2010"
.SH NAME
Robocut - it allows users to cut SVG files on a cutting plotter.
.SH SYNOPSIS
.B Robocut
.RI [ options ] ...
.SH DESCRIPTION
The \fIRobocut\fP program allows users of Inkscape to cut a 
SVG file.
.SH OPTIONS
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version information
.SH SEE ALSO
.BR X (1),
.SH AUTHOR
Robocut was written by Tim Hutt.
.PP
This manual page was written by Markus Schulz <schulz@alpharesearch.de>,
for the Debian project (and may be used by others).
